# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      #- name: Run a one-line script
      #  run: echo Hello, world!
      # - name: Email
      #   run: |
      #     printf "Subject: Goblog Master Update\n\nAn update to the master branch of the Goblog repo took place, we will start building again. Expect downtime & prepare for the worst" | ssmtp personal@codin.ro

      - name: Env
        run: |
          echo ::set-env name=db_user_goblog::$(grep db_user_goblog -F /home/pi/.bashrc | cut -d "=" -f 2)
          echo ::set-env name=db_pw_goblog::$(grep db_pw_goblog -F /home/pi/.bashrc | cut -d "=" -f 2)
          echo ::set-env name=db_host_goblog::$(grep db_host_goblog -F /home/pi/.bashrc | cut -d "=" -f 2)
          echo ::set-env name=db_name_goblog::$(grep db_name_goblog -F /home/pi/.bashrc | cut -d "=" -f 2)
          echo ::set-env name=certFile::$(grep certFile -F /home/pi/.bashrc | cut -d "=" -f 2)
          echo ::set-env name=keyFile::$(grep keyFile -F /home/pi/.bashrc | cut -d "=" -f 2)
          export db_user_goblog=$db_user_goblog
          export db_pw_goblog=$db_pw_goblog
          export db_name_goblog=$db_name_goblog
          export db_host_goblog=$db_host_goblog
          export certFile_goblog=$certFile
          export keyFile_goblog=$keyFile
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          docker container stop goblog;
          docker container rm goblog;
          docker image rm goblog:latest;
          rm -rf ~/repos/goblog
          cd ~/repos/
          git clone https://github.com/CodinMoldovanu/goblog && cd goblog
          docker build --tag goblog:latest . --no-cache
          docker run --publish 1333:1333 -e db_user_goblog -e db_pw_goblog -e db_name_goblog -e db_host_goblog -e keyFile_goblog -e certFile_goblog -v ~/repos:/certs --detach --name goblog goblog:latest
          cd frontend
          npm install
          npm run build
          cp -r dist ~/production/
      # - name: Email_Ending
      #   run: |
      #     printf "Subject: Goblog Master Update\n\nWorkflow ended!" | ssmtp personal@codin.ro

